// Code generated by Fluent generator. DO NOT EDIT.

package htmx

import (
	"strings"
	"testing"

	"github.com/jpl-au/fluent/html5/div"
)

func TestNew(t *testing.T) {
	d := div.New()
	w := New(d)

	if w == nil {
		t.Fatal("New() returned nil")
	}

	if w.node != d {
		t.Error("Wrapper does not wrap the provided node")
	}
}

func TestNodeInterfaceDelegation(t *testing.T) {
	d := div.New().ID("test")
	w := New(d)

	// Test Render
	html := string(w.Render())
	if !strings.Contains(html, `id="test"`) {
		t.Errorf("Render() delegation failed, got: %s", html)
	}

	// Test Nodes - should return non-nil slice (even if empty)
	nodes := w.Nodes()
	_ = nodes // Nodes() delegation successful if no panic
}

func TestHxGet(t *testing.T) {
	d := div.New()
	w := New(d)

	// Test HxGet method
	w.HxGet("test-value")

	html := string(d.Render())
	if !strings.Contains(html, "hx-get=\"test-value\"") {
		t.Errorf("HxGet() did not set attribute correctly, got: %s", html)
	}
}

func TestHxPost(t *testing.T) {
	d := div.New()
	w := New(d)

	// Test HxPost method
	w.HxPost("test-value")

	html := string(d.Render())
	if !strings.Contains(html, "hx-post=\"test-value\"") {
		t.Errorf("HxPost() did not set attribute correctly, got: %s", html)
	}
}

func TestHxPut(t *testing.T) {
	d := div.New()
	w := New(d)

	// Test HxPut method
	w.HxPut("test-value")

	html := string(d.Render())
	if !strings.Contains(html, "hx-put=\"test-value\"") {
		t.Errorf("HxPut() did not set attribute correctly, got: %s", html)
	}
}

func TestHxPatch(t *testing.T) {
	d := div.New()
	w := New(d)

	// Test HxPatch method
	w.HxPatch("test-value")

	html := string(d.Render())
	if !strings.Contains(html, "hx-patch=\"test-value\"") {
		t.Errorf("HxPatch() did not set attribute correctly, got: %s", html)
	}
}

func TestHxDelete(t *testing.T) {
	d := div.New()
	w := New(d)

	// Test HxDelete method
	w.HxDelete("test-value")

	html := string(d.Render())
	if !strings.Contains(html, "hx-delete=\"test-value\"") {
		t.Errorf("HxDelete() did not set attribute correctly, got: %s", html)
	}
}

func TestHxSwap(t *testing.T) {
	d := div.New()
	w := New(d)

	// Test HxSwap method
	w.HxSwap("test-value")

	html := string(d.Render())
	if !strings.Contains(html, "hx-swap=\"test-value\"") {
		t.Errorf("HxSwap() did not set attribute correctly, got: %s", html)
	}
}

func TestHxTarget(t *testing.T) {
	d := div.New()
	w := New(d)

	// Test HxTarget method
	w.HxTarget("test-value")

	html := string(d.Render())
	if !strings.Contains(html, "hx-target=\"test-value\"") {
		t.Errorf("HxTarget() did not set attribute correctly, got: %s", html)
	}
}

func TestHxTrigger(t *testing.T) {
	d := div.New()
	w := New(d)

	// Test HxTrigger method
	w.HxTrigger("test-value")

	html := string(d.Render())
	if !strings.Contains(html, "hx-trigger=\"test-value\"") {
		t.Errorf("HxTrigger() did not set attribute correctly, got: %s", html)
	}
}

func TestHxBoost(t *testing.T) {
	d := div.New()
	w := New(d)

	// Test HxBoost method
	w.HxBoost(true)

	html := string(d.Render())
	if !strings.Contains(html, "hx-boost=\"true\"") {
		t.Errorf("HxBoost() did not set attribute correctly, got: %s", html)
	}
}

func TestHxConfirm(t *testing.T) {
	d := div.New()
	w := New(d)

	// Test HxConfirm method
	w.HxConfirm("test-value")

	html := string(d.Render())
	if !strings.Contains(html, "hx-confirm=\"test-value\"") {
		t.Errorf("HxConfirm() did not set attribute correctly, got: %s", html)
	}
}

func TestHxVals(t *testing.T) {
	d := div.New()
	w := New(d)

	// Test HxVals method
	w.HxVals("test-value")

	html := string(d.Render())
	if !strings.Contains(html, "hx-vals=\"test-value\"") {
		t.Errorf("HxVals() did not set attribute correctly, got: %s", html)
	}
}

func TestHxHeaders(t *testing.T) {
	d := div.New()
	w := New(d)

	// Test HxHeaders method
	w.HxHeaders("test-value")

	html := string(d.Render())
	if !strings.Contains(html, "hx-headers=\"test-value\"") {
		t.Errorf("HxHeaders() did not set attribute correctly, got: %s", html)
	}
}

func TestHxIndicator(t *testing.T) {
	d := div.New()
	w := New(d)

	// Test HxIndicator method
	w.HxIndicator("test-value")

	html := string(d.Render())
	if !strings.Contains(html, "hx-indicator=\"test-value\"") {
		t.Errorf("HxIndicator() did not set attribute correctly, got: %s", html)
	}
}

func TestHxPushURL(t *testing.T) {
	d := div.New()
	w := New(d)

	// Test HxPushURL method with "true"
	w.HxPushURL("true")

	html := string(d.Render())
	if !strings.Contains(html, "hx-push-url=\"true\"") {
		t.Errorf("HxPushURL() did not set attribute correctly, got: %s", html)
	}

	// Test HxPushURL with custom URL
	d2 := div.New()
	w2 := New(d2)
	w2.HxPushURL("/custom/path")

	html2 := string(d2.Render())
	if !strings.Contains(html2, "hx-push-url=\"/custom/path\"") {
		t.Errorf("HxPushURL() with custom URL did not set attribute correctly, got: %s", html2)
	}

	// Test HxPushURL with "false"
	d3 := div.New()
	w3 := New(d3)
	w3.HxPushURL("false")

	html3 := string(d3.Render())
	if !strings.Contains(html3, "hx-push-url=\"false\"") {
		t.Errorf("HxPushURL() with false did not set attribute correctly, got: %s", html3)
	}
}

func TestHxExt(t *testing.T) {
	d := div.New()
	w := New(d)

	// Test HxExt method
	w.HxExt("test-value")

	html := string(d.Render())
	if !strings.Contains(html, "hx-ext=\"test-value\"") {
		t.Errorf("HxExt() did not set attribute correctly, got: %s", html)
	}
}

func TestHxSelect(t *testing.T) {
	d := div.New()
	w := New(d)

	// Test HxSelect method
	w.HxSelect("test-value")

	html := string(d.Render())
	if !strings.Contains(html, "hx-select=\"test-value\"") {
		t.Errorf("HxSelect() did not set attribute correctly, got: %s", html)
	}
}

func TestHxSelectOOB(t *testing.T) {
	d := div.New()
	w := New(d)

	// Test HxSelectOOB method
	w.HxSelectOOB("test-value")

	html := string(d.Render())
	if !strings.Contains(html, "hx-select-oob=\"test-value\"") {
		t.Errorf("HxSelectOOB() did not set attribute correctly, got: %s", html)
	}
}

func TestHxSwapOOB(t *testing.T) {
	d := div.New()
	w := New(d)

	// Test HxSwapOOB method
	w.HxSwapOOB("test-value")

	html := string(d.Render())
	if !strings.Contains(html, "hx-swap-oob=\"test-value\"") {
		t.Errorf("HxSwapOOB() did not set attribute correctly, got: %s", html)
	}
}

func TestHxReplaceUrl(t *testing.T) {
	d := div.New()
	w := New(d)

	// Test HxReplaceUrl method
	w.HxReplaceUrl("test-value")

	html := string(d.Render())
	if !strings.Contains(html, "hx-replace-url=\"test-value\"") {
		t.Errorf("HxReplaceUrl() did not set attribute correctly, got: %s", html)
	}
}

func TestHxParams(t *testing.T) {
	d := div.New()
	w := New(d)

	// Test HxParams method
	w.HxParams("test-value")

	html := string(d.Render())
	if !strings.Contains(html, "hx-params=\"test-value\"") {
		t.Errorf("HxParams() did not set attribute correctly, got: %s", html)
	}
}

func TestHxInclude(t *testing.T) {
	d := div.New()
	w := New(d)

	// Test HxInclude method
	w.HxInclude("test-value")

	html := string(d.Render())
	if !strings.Contains(html, "hx-include=\"test-value\"") {
		t.Errorf("HxInclude() did not set attribute correctly, got: %s", html)
	}
}

func TestHxSync(t *testing.T) {
	d := div.New()
	w := New(d)

	// Test HxSync method
	w.HxSync("test-value")

	html := string(d.Render())
	if !strings.Contains(html, "hx-sync=\"test-value\"") {
		t.Errorf("HxSync() did not set attribute correctly, got: %s", html)
	}
}

func TestHxPrompt(t *testing.T) {
	d := div.New()
	w := New(d)

	// Test HxPrompt method
	w.HxPrompt("test-value")

	html := string(d.Render())
	if !strings.Contains(html, "hx-prompt=\"test-value\"") {
		t.Errorf("HxPrompt() did not set attribute correctly, got: %s", html)
	}
}

func TestHxEncoding(t *testing.T) {
	d := div.New()
	w := New(d)

	// Test HxEncoding method
	w.HxEncoding("test-value")

	html := string(d.Render())
	if !strings.Contains(html, "hx-encoding=\"test-value\"") {
		t.Errorf("HxEncoding() did not set attribute correctly, got: %s", html)
	}
}

func TestHxPreserve(t *testing.T) {
	d := div.New()
	w := New(d)

	// Test HxPreserve method
	w.HxPreserve(true)

	html := string(d.Render())
	if !strings.Contains(html, "hx-preserve=\"true\"") {
		t.Errorf("HxPreserve() did not set attribute correctly, got: %s", html)
	}
}

func TestHxHistory(t *testing.T) {
	d := div.New()
	w := New(d)

	// Test HxHistory method with "false" to prevent caching
	w.HxHistory("false")

	html := string(d.Render())
	if !strings.Contains(html, "hx-history=\"false\"") {
		t.Errorf("HxHistory() did not set attribute correctly, got: %s", html)
	}
}

func TestHxHistoryElt(t *testing.T) {
	d := div.New()
	w := New(d)

	// Test HxHistoryElt method (boolean flag attribute)
	w.HxHistoryElt()

	html := string(d.Render())
	if !strings.Contains(html, "hx-history-elt=\"true\"") {
		t.Errorf("HxHistoryElt() did not set attribute correctly, got: %s", html)
	}
}

func TestHxDisable(t *testing.T) {
	d := div.New()
	w := New(d)

	// Test HxDisable method (boolean flag attribute, value is ignored)
	w.HxDisable()

	html := string(d.Render())
	if !strings.Contains(html, "hx-disable=\"true\"") {
		t.Errorf("HxDisable() did not set attribute correctly, got: %s", html)
	}
}

func TestHxDisabledElt(t *testing.T) {
	d := div.New()
	w := New(d)

	// Test HxDisabledElt method
	w.HxDisabledElt("test-value")

	html := string(d.Render())
	if !strings.Contains(html, "hx-disabled-elt=\"test-value\"") {
		t.Errorf("HxDisabledElt() did not set attribute correctly, got: %s", html)
	}
}

func TestHxDisinherit(t *testing.T) {
	d := div.New()
	w := New(d)

	// Test HxDisinherit method
	w.HxDisinherit("test-value")

	html := string(d.Render())
	if !strings.Contains(html, "hx-disinherit=\"test-value\"") {
		t.Errorf("HxDisinherit() did not set attribute correctly, got: %s", html)
	}
}

func TestHxInherit(t *testing.T) {
	d := div.New()
	w := New(d)

	// Test HxInherit method
	w.HxInherit("test-value")

	html := string(d.Render())
	if !strings.Contains(html, "hx-inherit=\"test-value\"") {
		t.Errorf("HxInherit() did not set attribute correctly, got: %s", html)
	}
}

func TestHxValidate(t *testing.T) {
	d := div.New()
	w := New(d)

	// Test HxValidate method
	w.HxValidate(true)

	html := string(d.Render())
	if !strings.Contains(html, "hx-validate=\"true\"") {
		t.Errorf("HxValidate() did not set attribute correctly, got: %s", html)
	}
}

func TestHxRequest(t *testing.T) {
	d := div.New()
	w := New(d)

	// Test HxRequest method
	w.HxRequest("test-value")

	html := string(d.Render())
	if !strings.Contains(html, "hx-request=\"test-value\"") {
		t.Errorf("HxRequest() did not set attribute correctly, got: %s", html)
	}
}

func TestHxVars(t *testing.T) {
	d := div.New()
	w := New(d)

	// Test HxVars method
	w.HxVars("test-value")

	html := string(d.Render())
	if !strings.Contains(html, "hx-vars=\"test-value\"") {
		t.Errorf("HxVars() did not set attribute correctly, got: %s", html)
	}
}

func TestHxOn(t *testing.T) {
	d := div.New()
	w := New(d)

	// Test HxOn method
	w.HxOn("test-value", "controller")

	html := string(d.Render())
	if !strings.Contains(html, "hx-on::test-value=\"controller\"") {
		t.Errorf("HxOn() did not set attribute correctly, got: %s", html)
	}
}

